# Generated by Django 3.2.7 on 2021-10-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0006_imgmarcas_nombrei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='precioa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
