# Generated by Django 3.2.7 on 2021-10-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0007_auto_20211027_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='descripciona',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='fotoa',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='marcaa',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='nombrea',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='precioa',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='tipoa',
            new_name='tipo',
        ),
    ]
