# Generated by Django 3.2.6 on 2021-10-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0003_imgmarcas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmarcas',
            name='foto',
            field=models.CharField(max_length=300),
        ),
    ]
