# Generated by Django 3.2.6 on 2021-10-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0004_alter_imgmarcas_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgmarcas',
            old_name='foto',
            new_name='fotoi',
        ),
    ]
