# Generated by Django 3.2.6 on 2021-10-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0005_rename_foto_imgmarcas_fotoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgmarcas',
            name='nombrei',
            field=models.CharField(default='', max_length=40),
        ),
    ]
